version: '3'

services:
  app: 
    container_name: app
    image: node:lts-alpine
    working_dir: /usr/app
    ports:
      - 8080:8080
    command: yarn dev
    volumes:
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge